// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozgeyilmazh/youtube-project/scrape-scheduler (interfaces: Client)

// Package scrape_scheduler is a generated GoMock package.
package scrape_scheduler

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// TriggerScraping mocks base method.
func (m *MockClient) TriggerScraping(arg0 context.Context, arg1, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerScraping", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// TriggerScraping indicates an expected call of TriggerScraping.
func (mr *MockClientMockRecorder) TriggerScraping(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerScraping", reflect.TypeOf((*MockClient)(nil).TriggerScraping), arg0, arg1, arg2)
}
