// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozgeyilmazh/youtube-project/quotes-api (interfaces: HandlerService)
//
// Generated by this command:
//
//	mockgen -destination=handler_mock.go -package=quotesapi . HandlerService
//

// Package quotesapi is a generated GoMock package.
package quotesapi

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHandlerService is a mock of HandlerService interface.
type MockHandlerService struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerServiceMockRecorder
	isgomock struct{}
}

// MockHandlerServiceMockRecorder is the mock recorder for MockHandlerService.
type MockHandlerServiceMockRecorder struct {
	mock *MockHandlerService
}

// NewMockHandlerService creates a new mock instance.
func NewMockHandlerService(ctrl *gomock.Controller) *MockHandlerService {
	mock := &MockHandlerService{ctrl: ctrl}
	mock.recorder = &MockHandlerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlerService) EXPECT() *MockHandlerServiceMockRecorder {
	return m.recorder
}

// FetchQuotes mocks base method.
func (m *MockHandlerService) FetchQuotes(ctx context.Context, page int) ([]QuotesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchQuotes", ctx, page)
	ret0, _ := ret[0].([]QuotesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchQuotes indicates an expected call of FetchQuotes.
func (mr *MockHandlerServiceMockRecorder) FetchQuotes(ctx, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchQuotes", reflect.TypeOf((*MockHandlerService)(nil).FetchQuotes), ctx, page)
}
