// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozgeyilmazh/youtube-project/quotes-api (interfaces: QuotesAPIClient)
//
// Generated by this command:
//
//	mockgen -destination=service_mock.go -package=quotesapi . QuotesAPIClient
//

// Package quotesapi is a generated GoMock package.
package quotesapi

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockQuotesAPIClient is a mock of QuotesAPIClient interface.
type MockQuotesAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockQuotesAPIClientMockRecorder
	isgomock struct{}
}

// MockQuotesAPIClientMockRecorder is the mock recorder for MockQuotesAPIClient.
type MockQuotesAPIClientMockRecorder struct {
	mock *MockQuotesAPIClient
}

// NewMockQuotesAPIClient creates a new mock instance.
func NewMockQuotesAPIClient(ctrl *gomock.Controller) *MockQuotesAPIClient {
	mock := &MockQuotesAPIClient{ctrl: ctrl}
	mock.recorder = &MockQuotesAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuotesAPIClient) EXPECT() *MockQuotesAPIClientMockRecorder {
	return m.recorder
}

// FetchQuotes mocks base method.
func (m *MockQuotesAPIClient) FetchQuotes(ctx context.Context, page int) ([]QuotesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchQuotes", ctx, page)
	ret0, _ := ret[0].([]QuotesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchQuotes indicates an expected call of FetchQuotes.
func (mr *MockQuotesAPIClientMockRecorder) FetchQuotes(ctx, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchQuotes", reflect.TypeOf((*MockQuotesAPIClient)(nil).FetchQuotes), ctx, page)
}
