// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozgeyilmazh/youtube-project/scraper-gateway (interfaces: ServiceQuotesDiscoveryClient)

// Package scraper_gateway is a generated GoMock package.
package scraper_gateway

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockServiceQuotesDiscoveryClient is a mock of ServiceQuotesDiscoveryClient interface.
type MockServiceQuotesDiscoveryClient struct {
	ctrl     *gomock.Controller
	recorder *MockServiceQuotesDiscoveryClientMockRecorder
}

// MockServiceQuotesDiscoveryClientMockRecorder is the mock recorder for MockServiceQuotesDiscoveryClient.
type MockServiceQuotesDiscoveryClientMockRecorder struct {
	mock *MockServiceQuotesDiscoveryClient
}

// NewMockServiceQuotesDiscoveryClient creates a new mock instance.
func NewMockServiceQuotesDiscoveryClient(ctrl *gomock.Controller) *MockServiceQuotesDiscoveryClient {
	mock := &MockServiceQuotesDiscoveryClient{ctrl: ctrl}
	mock.recorder = &MockServiceQuotesDiscoveryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceQuotesDiscoveryClient) EXPECT() *MockServiceQuotesDiscoveryClientMockRecorder {
	return m.recorder
}

// TriggerScrape mocks base method.
func (m *MockServiceQuotesDiscoveryClient) TriggerScrape(arg0 context.Context, arg1, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerScrape", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// TriggerScrape indicates an expected call of TriggerScrape.
func (mr *MockServiceQuotesDiscoveryClientMockRecorder) TriggerScrape(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerScrape", reflect.TypeOf((*MockServiceQuotesDiscoveryClient)(nil).TriggerScrape), arg0, arg1, arg2)
}
