// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozgeyilmazh/youtube-project/quotes-discovery (interfaces: ActivityQuotesAPIClient,Repository)

// Package quotesdiscovery is a generated GoMock package.
package quotesdiscovery

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockActivityQuotesAPIClient is a mock of ActivityQuotesAPIClient interface.
type MockActivityQuotesAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockActivityQuotesAPIClientMockRecorder
}

// MockActivityQuotesAPIClientMockRecorder is the mock recorder for MockActivityQuotesAPIClient.
type MockActivityQuotesAPIClientMockRecorder struct {
	mock *MockActivityQuotesAPIClient
}

// NewMockActivityQuotesAPIClient creates a new mock instance.
func NewMockActivityQuotesAPIClient(ctrl *gomock.Controller) *MockActivityQuotesAPIClient {
	mock := &MockActivityQuotesAPIClient{ctrl: ctrl}
	mock.recorder = &MockActivityQuotesAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivityQuotesAPIClient) EXPECT() *MockActivityQuotesAPIClientMockRecorder {
	return m.recorder
}

// FetchQuotes mocks base method.
func (m *MockActivityQuotesAPIClient) FetchQuotes(arg0 context.Context, arg1 int) ([]Quotes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchQuotes", arg0, arg1)
	ret0, _ := ret[0].([]Quotes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchQuotes indicates an expected call of FetchQuotes.
func (mr *MockActivityQuotesAPIClientMockRecorder) FetchQuotes(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchQuotes", reflect.TypeOf((*MockActivityQuotesAPIClient)(nil).FetchQuotes), arg0, arg1)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// BulkInsertData mocks base method.
func (m *MockRepository) BulkInsertData(arg0 context.Context, arg1 []Quotes) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkInsertData", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkInsertData indicates an expected call of BulkInsertData.
func (mr *MockRepositoryMockRecorder) BulkInsertData(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkInsertData", reflect.TypeOf((*MockRepository)(nil).BulkInsertData), arg0, arg1)
}
