// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozgeyilmazh/youtube-project/quotes-discovery (interfaces: HandlerWorkflow)

// Package quotesdiscovery is a generated GoMock package.
package quotesdiscovery

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	workflow "go.temporal.io/sdk/workflow"
)

// MockHandlerWorkflow is a mock of HandlerWorkflow interface.
type MockHandlerWorkflow struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerWorkflowMockRecorder
}

// MockHandlerWorkflowMockRecorder is the mock recorder for MockHandlerWorkflow.
type MockHandlerWorkflowMockRecorder struct {
	mock *MockHandlerWorkflow
}

// NewMockHandlerWorkflow creates a new mock instance.
func NewMockHandlerWorkflow(ctrl *gomock.Controller) *MockHandlerWorkflow {
	mock := &MockHandlerWorkflow{ctrl: ctrl}
	mock.recorder = &MockHandlerWorkflowMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlerWorkflow) EXPECT() *MockHandlerWorkflowMockRecorder {
	return m.recorder
}

// FetchQuotes mocks base method.
func (m *MockHandlerWorkflow) FetchQuotes(arg0 workflow.Context, arg1 int) ([]Quotes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchQuotes", arg0, arg1)
	ret0, _ := ret[0].([]Quotes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchQuotes indicates an expected call of FetchQuotes.
func (mr *MockHandlerWorkflowMockRecorder) FetchQuotes(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchQuotes", reflect.TypeOf((*MockHandlerWorkflow)(nil).FetchQuotes), arg0, arg1)
}
