// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozgeyilmazh/youtube-project/quotes-discovery (interfaces: WorkflowActivity)

// Package quotesdiscovery is a generated GoMock package.
package quotesdiscovery

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockWorkflowActivity is a mock of WorkflowActivity interface.
type MockWorkflowActivity struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowActivityMockRecorder
}

// MockWorkflowActivityMockRecorder is the mock recorder for MockWorkflowActivity.
type MockWorkflowActivityMockRecorder struct {
	mock *MockWorkflowActivity
}

// NewMockWorkflowActivity creates a new mock instance.
func NewMockWorkflowActivity(ctrl *gomock.Controller) *MockWorkflowActivity {
	mock := &MockWorkflowActivity{ctrl: ctrl}
	mock.recorder = &MockWorkflowActivityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowActivity) EXPECT() *MockWorkflowActivityMockRecorder {
	return m.recorder
}

// BulkInsertData mocks base method.
func (m *MockWorkflowActivity) BulkInsertData(arg0 context.Context, arg1 []Quotes) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkInsertData", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkInsertData indicates an expected call of BulkInsertData.
func (mr *MockWorkflowActivityMockRecorder) BulkInsertData(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkInsertData", reflect.TypeOf((*MockWorkflowActivity)(nil).BulkInsertData), arg0, arg1)
}

// FetchQuotes mocks base method.
func (m *MockWorkflowActivity) FetchQuotes(arg0 context.Context, arg1 int) ([]Quotes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchQuotes", arg0, arg1)
	ret0, _ := ret[0].([]Quotes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchQuotes indicates an expected call of FetchQuotes.
func (mr *MockWorkflowActivityMockRecorder) FetchQuotes(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchQuotes", reflect.TypeOf((*MockWorkflowActivity)(nil).FetchQuotes), arg0, arg1)
}
